### ISSUE TITLE
Erroneous math in maximum likelihood estimation document

### ISSUE THREAD

**Issue by tomage** [unpingco/Python-for-Signal-Processing#5]
Hi!

I was reading [Maximum Likelihood Estimation](http://nbviewer.ipython.org/github/melund/Python-for-Signal-Processing/blob/master/Maximum_likelihood.ipynb) (direct link to the github file [here](https://github.com/unpingco/Python-for-Signal-Processing/blob/master/Maximum_likelihood.ipynb)) and noticed that there seems to be a tiny error in one of the formula, namely in the "Confidence Intervals" section.

Now [here](https://github.com/unpingco/Python-for-Signal-Processing/blob/master/Maximum_likelihood.ipynb#L347)'s a link to the exact line I have issue with.

Namely, it seems the denominator in the probability calculations ought be "200", not "100". This is already mended in the nest formula, where we have i.e. the fraction "9999/200".

**Comment by unpingco** [comment]
Fixed! Thanks for the note.
