### ISSUE TITLE
How to apply windowing in time and frequency domain

### ISSUE THREAD

**Issue by manasdas17** [unpingco/Python-for-Signal-Processing#6]
Hi,
   The windowing you are applying to different signals in Windowing.ipynb is in time-domain or frequency domain?
If i have a signal e.g. signal1=numpy.ones((1,50)) and i am applying windowing to it as 
      wt=numpy.transpose(numpy.kaiser(50,2.5))
      signal = signal1*wt.
Is it the correct way of applying windowing?
How to apply windowing in frequency domain?

**Comment by unpingco** [comment]
Yes, you are doing it correctly. Windowing only makes sense in the time domain. The text in the book has more explanation than the material on the blog.

Good luck !
