### ISSUE TITLE
Expectation_Maximization notebook: name 'Lf' is not defined error from like 319 

### ISSUE THREAD

**Issue by 00krishna** [unpingco/Python-for-Signal-Processing#8]
Hello. I was working with this really great notebook, but noticed an error at the very bottom. Line 319 says 

    z=Lf(xs,mua_step[:,None],mub_step[:,None,None]).sum(axis=2) # numpy broadcasting

So the Lf variable was defined in the scope of the run() function, but not in the global scope. So trying to run the Lf() function is generating the error. 

I fixed it by adding this line just above line 319:

    Lf=sympy.lambdify((x,mu_a,mu_b), sympy.log(abs(L)),'numpy')

So the total code looks like:

    Lf=sympy.lambdify((x,mu_a,mu_b), sympy.log(abs(L)),'numpy')
    z=Lf(xs,mua_step[:,None],mub_step[:,None,None]).sum(axis=2) # numpy broadcasting

Hope this helps.

**Comment by unpingco** [comment]
Fixed! Thanks for the notice.
